language: go
go:
  - 1.13.x
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'

sudo: false
install: true

git:
  depth: 1

notifications:
  email: true

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.24.0

script:
  - golangci-lint run
  - go test -v ./...